github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

tasks:
  - name: demo
    init: |
      curl -sL --http1.1 https://cnfl.io/cli | sh -s -- -b /home/gitpod/.local/bin/ && \
      pip install -r requirements.txt